#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.."; pwd)"


has() {
	local cmd="$1"
	which "$cmd" >/dev/null 2>&1
}


echo-stderr() {
	local message="$*"
	printf "%s\n" "$message" 1>&2
}


throw() {
	local message="$*"
	echo-stderr "error: $message"
	false
}


usage() {
	cat - 1>&2 <<-EOS
usage: generate-assigned-numbers [<options>]

OPTIONS
	-h, --help    print this usage
EOS
}


usage-error() {
	local message="$*"
	echo-stderr "$message"
	usage
	false
}


main() {
	(cd "$BASE_DIR"
		git submodule update --init --recursive
		swift run BLEAssignedNumbersGenerator ./Resources/bluetooth-SIG-public | tee ./Sources/BLEAssignedNumbers/AssignedNumbers.generated.swift
	)
}


case "$*" in
	--help | -h)
		usage
		false ;;
	*)
		main "$@" ;;
esac

