name: Release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: macos-latest 

    permissions:
      contents: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: recursive

      - name: Setup Swift
        uses: swift-actions/setup-swift@e1dca7c4a36344146bbc2803f0d538462477bb37 # v2.0.0
        with:
          swift-version: '5.10'

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .build
          key: spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-

      - name: Build
        run: |
          swift build

      - name: Upload Artifacts
        run: |
          gh release create "${{ github.ref_name }}" .build/arm64-apple-macosx/debug/ble
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          
