name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: macos-latest 

    permissions:
      contents: read
      checks: write

    strategy:
      matrix:
        os:
          - macOS
          - iOS
          - watchOS
          - tvOS
          # XXX: visionOS is not installed on macos-latest...
          # - visionOS

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: recursive

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .build
          key: spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-

      - name: Setup jq
        uses: dcarbone/install-jq-action@8867ddb4788346d7c22b72ea2e2ffe4d514c7bcb # v2.1.0

      - name: Run tests
        run: |
          make "test-${{ matrix.os }}"
        env:
          DEVELOPER_DIR: /Applications/Xcode_16_beta_4.app

      - name: Upload Logs
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: always() && matrix.os != 'macos'
        with:
          name: "test-${{ matrix.os }}-logs"
          path: |
            Logs/**/*.log
            build/reports/junit-*.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95 # v4.2.1
        if: always() && matrix.os != 'macos'
        with:
          report_paths: |
            build/reports/junit-*.xml
